### ISSUE TITLE
项目开始前的注意事项

### ISSUE THREAD

**Issue by harryisfish** [Tymon42/stu_mgsys_20#1]
### 背景  
作业要求使用 git 远程协作开发，所以大家就尽量抱着学习的心态来使用 git 和 Github 的各种功能来协作。开发相关的交流就尽量放在 Issues 中，模块化后的形成的任务放在 Projects 中的看板中。  
#### 熟悉 git 代码管理  

1. 提交、推送、拉取代码
2. 回溯
#### 熟悉 Github  

1. 项目（repo）页布局
2. Issues、Kanban 的使用
3. 会提交 Pull requests

**Comment by harryisfish** [comment]
@xiesnowt @JulienZeng 
可以看一下这个 issue ，如果有现成的函数，可以直接把函数的功能名字写在这里。

**Comment by harryisfish** [comment]
也可以随便在这条 issus 下面回复一句，感受一下怎么用 Github 上面交流。

**Comment by JulienZeng** [comment]
链表部分我来吧，包括增删改查（4,5,6,7）或者其他部分的

**Comment by harryisfish** [comment]
> 链表部分我来吧，包括增删改查（4,5,6,7）或者其他部分的

收到，把链表最先做了也好。

**Comment by JulienZeng** [comment]
关于结构体，数据这块我这样写
`typedef struct Data
{
    int id;
    char name[64];
    int colid;
    int sexid;
    float score[4];
}Data;`

链表这里我这样写
`typedef struct Node 
{
    Data data;
    Node *next;
}Node;`

**Comment by xiesnowt** [comment]
@JulienZeng
你链表函数那一块写了吗，写了发我看看

**Comment by JulienZeng** [comment]
@xiesnowt 
链表的函数我就是一个结构体，里面包含data和*next，你排序的话其实把data的内容改了就可以了，next不用改变的。

**Comment by xiesnowt** [comment]
@JulienZeng
收到

**Comment by xiesnowt** [comment]
@Tymon42 
咱两工作怎么分？
我写（1，2，3）？

**Comment by harryisfish** [comment]
> @Tymon42
> 咱两工作怎么分？
> 我写（1，2，3）？

Ok，那我现在写4、5、6

**Comment by xiesnowt** [comment]
@Tymon42
曾写4567
