### ISSUE TITLE
TODO: 定义头节点

### ISSUE THREAD

**Issue by harryisfish** [Tymon42/stu_mgsys_20#6]
在 index.c 的 line: 14  ，请 @JulienZeng 稍后完成定义头节点的代码。

**Comment by harryisfish** [comment]
已完成头节点空间分配，等待读取学生信息部分功能完成。

**Comment by JulienZeng** [comment]
头节点只需在main函数中进行
`list = CreateList();
colist = CreateList();
sexlist = CreateList();`
即可

**Comment by harryisfish** [comment]
收到
